language: cpp
compiler: gcc
matrix:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
      env:
         - MATRIX_EVAL="CC=gcc-5 && CXX=g++-5"
before_install:
  - eval "$(MATRIX_EVAL)"

script:
  - make
notifications:
  slack:
    secure: rninlqy8TBXYyKkCTGzoMZxlEp14Nb7nAN2zFTP4cVjNXOWiLEqgARj1JYJx3N/vZgQdT7dqCEBFITxSL+WzC6CBl1dSazggWnBlQrFDz55oXiDU6qp4GHUR5qeESNogVZhhZvoJecA7q9zphdowtjkmaNH/0et3ifsn+62ibxt1Jd3tBVruvPLjYY7NY7cojPg17moAayjtbtgsF3lHgtGr6Z3NfHT3/diZ0JIYtbadlhWDVShKNfHR2zclE3pOtAkY/RCF5r4PlBWdMIFXRTOVTDwT8Glh3tVb7r6olKeI4lh+Sfl2uzuYX/AXQKY9grXUNmNyVK7YCSmlRYtVaiYcj06CdxNuW5w8GcYkCo+4+EmMwA6ncuywa57+nRFzxv+zI62dudY6tmPigY4yhDjLkvwpshYO2QQTu+nZ5Zg8QwbB09wkifC3rTpoGxRH83s6nABsLyq12b+FnPzQOCJSxjcZ5XHlZqL3P5S03Le/Nn40u8dMjKO4jeQK5bG1mKBrtUa6b6ihjajqa7/KRehEnCKQl9DKWL4W3iyCgHx11p46lzWdSX7yTkHql+3pCeyVFwJ77X4forZuoqOrP+fYYlxaro/Vs1k4KQR/VTb2c2iE3PKr041ZFOcheBPJMZCeLI4dP9kCnsZf/+i+uTxASnUObSqz9UiJHh/9K40=
